# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ main ]
    tags: ["v*"]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        scalaVersion: ["2.11", "2.12"]
        sparkVersion: ["2.0", "2.1", "2.2", "2.3", "2.4"]
        exclude:
          - scalaVersion: "2.12"
            sparkVersion: "2.0"
          - scalaVersion: "2.12"
            sparkVersion: "2.1"
          - scalaVersion: "2.12"
            sparkVersion: "2.2"
          - scalaVersion: "2.12"
            sparkVersion: "2.3"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
    - name: Build with Gradle
      run: ./gradlew clean build -Pscala-version=${{ matrix.scalaVersion }} -Pspark-version=${{ matrix.sparkVersion }}
