# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: releaseSingleVersion

on:
  workflow_dispatch:
    inputs:
      publishSnapshot:
        description: 'Publish Snapshot'
        required: true
        default: 'false'
      sparkVersion:
        description: 'Spark version'
        required: true
      scalaVersion:
        description: 'Scala version'
        required: true

jobs:
  release:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
    - name: Build and publish
      run: |
        export GPG_TTY=$(tty)
        echo $PGP_SECRET | base64 --decode > /home/runner/secring.gpg
        ./gradlew clean build publishToSonatype closeAndReleaseSonatypeStagingRepository -Pscala-version=${{ github.event.inputs.scalaVersion }} -Pspark-version=${{ github.event.inputs.sparkVersion }} -Pfast -Psigning.secretKeyRingFile=/home/runner/secring.gpg -Psigning.password=$PGP_PASSPHRASE -Psigning.keyId=$PGP_KEY_ID
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
